language: java
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip
  - unzip -qq apache-maven-3.5.0-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$M2_HOME/bin:$PATH
  - echo "MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx1g -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS'" > ~/.mavenrc

install:
  -

matrix:
   fast_finish: true
   include:
   -  jdk: oraclejdk8
      env:
      - DESC="Install Java 8"
      - CMD="mvn clean install"

after_success:
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server><server><id>website</id><username>\${env.WEBSITE_USER}</username><password>\${env.WEBSITE_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn site site-deploy --settings ~/settings.xml

cache:
  directories:
  - ~/.m2
